# Variables

@baseUrl = http://localhost:3000

# Login
# @name login
POST {{ baseUrl }}/login
Accept: application/json 
Content-Type: application/json

{
    "email": "teste@teste.com.br",
    "password": "123"
}
###